permalink: /:year/:month/:day/:title.html
url: "http://adventure.dynamicprogrammer.com"
blog_url: "http://blog.dynamicprogrammer.com"
rss_url: "http://feeds.feedburner.com/DynamicSki"
author: "Hernan Garcia"
name: "Dynamic Ski"
destination: ../heroku_adventure/_site/
lcb: "{{"
rcb: "}}"
