permalink: /:year/:month/:day/:title.html
url: "http://outdoors.dynamicprogrammer.com"
blog_url: "http://blog.dynamicprogrammer.com"
photo_url: "http://photos.dynamicprogrammer.com"
rss_url: "http://feeds.feedburner.com/Outdoors"
author: "Hernan Garcia"
name: "Outdoors"
destination: ../heroku_adventure/_site/
lcb: "{{"
rcb: "}}"
